apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test-pod
spec:
  containers:
  - name: stress-container
    image: polinux/stress
    command:
    - stress
    args:
    - "--cpu"
    - "4"               # Number of CPU workers
    - "--timeout"
    - "60s"            # Run for 600 seconds (10 minutes)
    resources:
      requests:
        memory: "500Mi"  # Minimum memory request
        cpu: "1"         # Minimum CPU request
      limits:
        memory: "1Gi"    # Maximum memory usage
        cpu: "4"         # Maximum CPU usage
  tolerations:
  - key: "node.kubernetes.io/memory-pressure"
    operator: "Exists"
  nodeSelector:
    kubernetes.io/hostname: <node-name>