apiVersion: v1
kind: Pod
metadata:
  name: disk-latency-test
spec:
  containers:
  - name: fio
    image: alpine
    command: ["sh", "-c", "apk add --no-cache fio && fio --name=test --ioengine=sync --rw=randwrite --bs=4k --size=1G --numjobs=1 --runtime=60 --time_based --group_reporting"]
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/test
  volumes:
  - name: test-volume
    emptyDir: {}
  nodeSelector:
    kubernetes.io/hostname: <node-name>
  restartPolicy: Never