apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
spec:
  containers:
  - name: stress
    image: progrium/stress
    command: ["stress", "--vm", "2", "--vm-bytes", "6G", "--timeout", "30s"]
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "7Gi"
  nodeSelector:
    kubernetes.io/hostname: <node-name>
  restartPolicy: Never